import { ReTreeListContainer } from './re-tree-list-container';
import {ReferencableTester, refTesterRef} from "../../../test/referencable-tester";
import {Middle2WithChildren, ReChild3, ReChild4, RootWithChildren} from "../../../test/referencables-with-children";

describe('ReferencableTreeListContainer', () => {
  it('should create an instance', () => {
    let tester = new ReferencableTester()
    expect(new ReTreeListContainer(tester, 'refName',  refTesterRef.references.test)).toBeTruthy();
  });

  it("should give true if the remove and remove inverse chain triggered an element removal without removing element from different container", () => {
    let tester = new RootWithChildren()
    let middle = new Middle2WithChildren()
    let elem1 = new ReChild3()
    let elem2 = new ReChild4()
    expect(tester.child2.remove(middle)).toBeFalse()
    tester.link3.push(elem1)
    tester.link4.push(elem2)
    tester.child2.push(middle)
    middle.child3.push(elem1)
    middle.child4.push(elem2)
    expect(tester.link3.length).toBe(1)
    expect(tester.link4.length).toBe(1)
    expect(tester.link3).toContain(elem1)
    expect(tester.link4).toContain(elem2)
    expect(middle.child3.length).toBe(1)
    expect(middle.child4.length).toBe(1)
    expect(middle.child3).toContain(elem1)
    expect(middle.child4).toContain(elem2)
    expect(elem1.link1.length).toBe(1)
    expect(elem2.link1.length).toBe(1)
    expect(elem1.link1).toContain(tester)
    expect(elem2.link1).toContain(tester)
    expect(elem1.parentPointer).toBeDefined()
    expect(elem2.parentPointer).toBeDefined()
    expect(elem1.parentPointer?.value).toEqual(middle)
    expect(elem2.parentPointer.value).toEqual(middle)
    expect(tester.child2.remove(middle)).toBeTrue()
    expect(tester.child2.length).toBe(0)
    expect(tester.link3.length).toBe(1)
    expect(tester.link4.length).toBe(1)
    expect(middle.child3.length).toBe(1)
    expect(middle.child4.length).toBe(1)
    expect(elem1.link1.length).toBe(1)
    expect(elem2.link1.length).toBe(1)
    expect(elem1.parentPointer).toBeDefined()
    expect(elem2.parentPointer).toBeDefined()
    expect(elem1.parentPointer?.value).toEqual(middle)
    expect(elem2.parentPointer.value).toEqual(middle)
  });

  it("should give true if the removeCascade and remove inverse chain triggered an element removal, also removing it from other containers if required reference is deleted", () => {
    let tester = new RootWithChildren()
    let middle = new Middle2WithChildren()
    let elem1 = new ReChild3()
    let elem2 = new ReChild4()
    expect(tester.child2.removeCascade(middle)).toBeFalse()
    tester.link3.push(elem1)
    tester.link4.push(elem2)
    tester.child2.push(middle)
    middle.child3.push(elem1)
    middle.child4.push(elem2)
    expect(tester.link3.length).toBe(1)
    expect(tester.link4.length).toBe(1)
    expect(tester.link3).toContain(elem1)
    expect(tester.link4).toContain(elem2)
    expect(middle.child3.length).toBe(1)
    expect(middle.child4.length).toBe(1)
    expect(middle.child3).toContain(elem1)
    expect(middle.child4).toContain(elem2)
    expect(elem1.link1.length).toBe(1)
    expect(elem2.link1.length).toBe(1)
    expect(elem1.link1).toContain(tester)
    expect(elem2.link1).toContain(tester)
    expect(elem1.parentPointer).toBeDefined()
    expect(elem2.parentPointer).toBeDefined()
    expect(elem1.parentPointer?.value).toEqual(middle)
    expect(elem2.parentPointer.value).toEqual(middle)
    expect(tester.child2.removeCascade(middle)).toBeTrue()
    expect(tester.child2.length).toBe(0)
    expect(tester.link3.length).toBe(0)
    expect(tester.link4.length).toBe(0)
    expect(middle.child3.length).toBe(0)
    expect(middle.child4.length).toBe(0)
    expect(elem1.link1.length).toBe(0)
    expect(elem2.link1.length).toBe(0)
    expect(elem1.parentPointer?.value).toBeUndefined()
    expect(elem2.parentPointer.value).toBeUndefined()
  })
});
